# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
apt-get update
apt-get install -y \
  composer \
  php-bcmath \
  php-cli \
  php-gmp \
  php-json \
  php-uuid \
  php-xdebug \
  php-xml \
  php-zip \
  unzip
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eoan64"
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "../../../", "/home/vagrant/uuid", type: "rsync"

  config.vm.provider "virtualbox" do |v|
    v.name = "ramsey-uuid-linux"
  end
end
